'use strict';

/**
 * AiManager — GenAI-driven icebreaker response generation.
 *
 * All spoken text the bot produces (intro, per-participant prompts,
 * acknowledgements, skip notices, wrap-up) is generated by a large language
 * model rather than pulled from a fixed script.
 *
 * Operator-customisable instructions
 * -----------------------------------
 * The bot's personality and activity rules are controlled by a plain-text
 * "instructions" block, resolved in this priority order:
 *
 *   1. ICEBREAKER_INSTRUCTIONS environment variable  (inline text)
 *   2. File pointed to by ICEBREAKER_INSTRUCTIONS_FILE env var
 *   3. instructions.txt in the project root (if present)
 *   4. Built-in default instructions (professional icebreaker host)
 *
 * AI provider
 * -----------
 * Two providers are supported, selected automatically from env vars:
 *
 *   Azure OpenAI (default for Azure deployments):
 *     AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_API_KEY, AZURE_OPENAI_DEPLOYMENT
 *
 *   Standard OpenAI (fallback):
 *     OPENAI_API_KEY  (optionally: OPENAI_MODEL)
 *
 * If neither provider is configured the manager operates in "fallback" mode,
 * returning deterministic scripted text from IcebreakerSession so the bot
 * still works without an AI key.
 */

const fs = require('fs');
const path = require('path');
const logger = require('./logger');

// ---------------------------------------------------------------------------
// Default instructions
// ---------------------------------------------------------------------------

const DEFAULT_INSTRUCTIONS = `\
You are an enthusiastic, warm, and inclusive icebreaker host for a Microsoft Teams meeting.
Your goal is to help participants feel comfortable and excited to connect with each other.

Guidelines:
- Keep energy positive, professional, and welcoming.
- Acknowledge each person's response genuinely before moving to the next participant.
- Encourage everyone to participate but never pressure anyone.
- Adapt your tone to what participants share — be empathetic, curious, or celebratory as appropriate.
- Keep things moving at a comfortable pace.
`;

// ---------------------------------------------------------------------------
// Context hint constants (what the bot needs to say at each moment)
// ---------------------------------------------------------------------------

const HINT = Object.freeze({
  INTRO: 'intro',
  PARTICIPANT_PROMPT: 'participant_prompt',
  ACKNOWLEDGEMENT: 'acknowledgement',
  SKIP: 'skip',
  WRAPUP: 'wrapup',
  NO_PARTICIPANTS: 'no_participants',
});

// ---------------------------------------------------------------------------
// TTS formatting rules injected into every system prompt
// ---------------------------------------------------------------------------

const TTS_RULES = `\
CRITICAL — your output will be read aloud via text-to-speech:
- Return ONLY the words to be spoken. No markdown, no bullet points, no stage directions.
- Use commas and natural pauses instead of dashes or semicolons.
- Spell out numbers and abbreviations.
- Keep responses concise: aim for 2–4 sentences unless the task genuinely requires more.
- Do not start with filler like "Sure!" or "Of course!".
`;

// ---------------------------------------------------------------------------
// AiManager class
// ---------------------------------------------------------------------------

class AiManager {
  constructor() {
    this._instructions = this._loadInstructions();
    this._client = null;  // lazily initialised
    this._model = null;
    this._isAzure = false;

    try {
      this._initClient();
    } catch (err) {
      logger.warn(`AiManager: could not initialise AI client — falling back to scripted responses. (${err.message})`);
    }
  }

  // -------------------------------------------------------------------------
  // Public API
  // -------------------------------------------------------------------------

  /**
   * Generate the text the bot should speak right now.
   *
   * @param {import('./icebreakerActivity').IcebreakerSession} session
   * @param {string} hint  - One of the HINT constants
   * @param {object} [extra]
   * @param {object} [extra.participant]  - { id, name } for participant_prompt / skip
   * @param {string} [extra.spokenText]  - What the participant said (for acknowledgement)
   * @returns {Promise<string>} Plain text to be read aloud
   */
  async generateResponse(session, hint, extra = {}) {
    // No AI configured — fall back to scripted text immediately
    if (!this._client) {
      return this._scriptedFallback(session, hint, extra);
    }

    const systemPrompt = this._buildSystemPrompt(session);
    const userMessage = this._buildUserMessage(session, hint, extra);

    const messages = [
      { role: 'system', content: systemPrompt },
      // Conversation history gives the model full context of what has already
      // been said so acknowledgements and prompts feel natural and varied.
      ...session.getConversationHistory(),
      { role: 'user', content: userMessage },
    ];

    try {
      const completion = await this._client.chat.completions.create({
        model: this._model,
        messages,
        max_tokens: 220,
        temperature: 0.85,
      });

      const text = (completion.choices[0]?.message?.content || '').trim();
      if (!text) throw new Error('Empty response from AI');

      // Record the bot's response in the session history so future AI calls
      // can see what was already said and avoid repetition.
      session.addToHistory('assistant', text);
      logger.debug(`AI response [${hint}]: "${text.slice(0, 80)}..."`);
      return text;
    } catch (err) {
      logger.error(`AI generation failed (hint=${hint}): ${err.message}`);
      return this._scriptedFallback(session, hint, extra);
    }
  }

  /** Whether an AI client is configured and available. */
  get isConfigured() {
    return this._client !== null;
  }

  // -------------------------------------------------------------------------
  // Prompt construction
  // -------------------------------------------------------------------------

  _buildSystemPrompt(session) {
    const participantList =
      session.participants.length > 0
        ? session.participants.map((p) => `- ${p.name}`).join('\n')
        : '(not yet known — participants will introduce themselves)';

    const remaining = session.participants.filter((p) => !p.hasGone);
    const done = session.participants.filter((p) => p.hasGone);

    return [
      this._instructions,
      '',
      TTS_RULES,
      '',
      '## Current meeting context',
      `Activity: ${session.activityName}`,
      `Phase: ${session.phase}`,
      '',
      '## Participants',
      participantList,
      '',
      `Turns completed: ${done.length}`,
      `Turns remaining: ${remaining.length}`,
    ].join('\n');
  }

  /**
   * Build the user-role instruction that tells the model exactly what to produce.
   */
  _buildUserMessage(session, hint, extra) {
    const { participant, spokenText } = extra;

    switch (hint) {
      case HINT.INTRO:
        return (
          `Generate a warm, energetic welcome message that:\n` +
          `1. Introduces you as the icebreaker host.\n` +
          `2. Announces the activity: "${session.activityName}".\n` +
          `3. Explains the rules clearly and briefly.\n` +
          `4. Signals that you will go around and ask each person in turn.`
        );

      case HINT.PARTICIPANT_PROMPT: {
        const name = participant?.name || 'the next participant';
        const prevNames = session.participants
          .filter((p) => p.hasGone)
          .map((p) => p.name)
          .join(', ');
        const prevContext = prevNames
          ? `The following people have already gone: ${prevNames}.`
          : 'This is the first person to go.';
        return (
          `Generate a prompt for ${name} to take their turn in the "${session.activityName}" activity. ` +
          `${prevContext} ` +
          `Address ${name} directly. ` +
          `If the activity is "Would You Rather", invent a fresh, original question you haven't asked yet.`
        );
      }

      case HINT.ACKNOWLEDGEMENT: {
        const name = participant?.name || 'the participant';
        const said = spokenText
          ? `They said: "${spokenText}".`
          : 'They gave a response (transcript unavailable).';
        return (
          `${name} just took their turn. ${said} ` +
          `Generate a brief, genuine, varied acknowledgement of what they shared. ` +
          `Do NOT repeat their words back verbatim. Be warm and move things forward.`
        );
      }

      case HINT.SKIP: {
        const name = participant?.name || 'the participant';
        return (
          `${name} did not respond in time. ` +
          `Generate a kind, brief message that: ` +
          `acknowledges them without embarrassing them and smoothly moves on to the next person.`
        );
      }

      case HINT.WRAPUP: {
        const names = session.participants.map((p) => p.name).join(', ');
        return (
          `The icebreaker is complete. All participants (${names || 'the group'}) have had their turn. ` +
          `Generate a warm, upbeat closing message that thanks everyone and ` +
          `wishes the meeting well. Keep it to 2–3 sentences.`
        );
      }

      case HINT.NO_PARTICIPANTS:
        return (
          `You have just joined the meeting but cannot see any participants yet. ` +
          `Generate a friendly message explaining this and inviting people to say hello ` +
          `or check that your app has the right permissions.`
        );

      default:
        return `Generate a friendly, brief statement appropriate for an icebreaker meeting host.`;
    }
  }

  // -------------------------------------------------------------------------
  // Scripted fallback (used when no AI is configured or the AI call fails)
  // -------------------------------------------------------------------------

  _scriptedFallback(session, hint, extra) {
    const { participant } = extra;
    switch (hint) {
      case HINT.INTRO:
        return session.getIntroScript();
      case HINT.PARTICIPANT_PROMPT:
        return participant ? session.getParticipantPrompt(participant) : "Who would like to go next?";
      case HINT.ACKNOWLEDGEMENT:
        return session.getRandomAcknowledgement();
      case HINT.SKIP:
        return session.getSkipScript(participant?.name || 'participant');
      case HINT.WRAPUP:
        return session.getWrapUpScript();
      case HINT.NO_PARTICIPANTS:
        return (
          "I don't see any participants yet. Please make sure I have permission to see " +
          "meeting participants, and feel free to say hello to get started!"
        );
      default:
        return "Thank you!";
    }
  }

  // -------------------------------------------------------------------------
  // Client initialisation
  // -------------------------------------------------------------------------

  _initClient() {
    // Dynamically require so that missing env vars don't crash at import time
    const { AzureOpenAI, OpenAI } = require('openai');

    if (process.env.AZURE_OPENAI_ENDPOINT && process.env.AZURE_OPENAI_API_KEY) {
      const deployment = process.env.AZURE_OPENAI_DEPLOYMENT || 'gpt-4o';
      logger.info(`AiManager: using Azure OpenAI (deployment: ${deployment})`);
      this._client = new AzureOpenAI({
        endpoint: process.env.AZURE_OPENAI_ENDPOINT,
        apiKey: process.env.AZURE_OPENAI_API_KEY,
        apiVersion: process.env.AZURE_OPENAI_API_VERSION || '2024-10-21',
        deployment,
      });
      this._model = deployment;
      this._isAzure = true;
    } else if (process.env.OPENAI_API_KEY) {
      const model = process.env.OPENAI_MODEL || 'gpt-4o-mini';
      logger.info(`AiManager: using OpenAI (model: ${model})`);
      this._client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
      this._model = model;
    } else {
      throw new Error(
        'No AI provider configured. Set AZURE_OPENAI_ENDPOINT + AZURE_OPENAI_API_KEY ' +
          'for Azure OpenAI, or OPENAI_API_KEY for standard OpenAI.'
      );
    }
  }

  // -------------------------------------------------------------------------
  // Instructions loading
  // -------------------------------------------------------------------------

  _loadInstructions() {
    // 1. Inline env var
    if (process.env.ICEBREAKER_INSTRUCTIONS) {
      logger.info('AiManager: loaded instructions from ICEBREAKER_INSTRUCTIONS env var');
      return process.env.ICEBREAKER_INSTRUCTIONS.trim();
    }

    // 2. File path from env var
    if (process.env.ICEBREAKER_INSTRUCTIONS_FILE) {
      try {
        const text = fs.readFileSync(process.env.ICEBREAKER_INSTRUCTIONS_FILE, 'utf8').trim();
        logger.info(`AiManager: loaded instructions from ${process.env.ICEBREAKER_INSTRUCTIONS_FILE}`);
        return text;
      } catch (err) {
        logger.warn(`AiManager: could not read ICEBREAKER_INSTRUCTIONS_FILE: ${err.message}`);
      }
    }

    // 3. Default instructions.txt in project root
    const defaultFile = path.join(__dirname, '..', 'instructions.txt');
    if (fs.existsSync(defaultFile)) {
      try {
        const text = fs.readFileSync(defaultFile, 'utf8').trim();
        logger.info('AiManager: loaded instructions from instructions.txt');
        return text;
      } catch (err) {
        logger.warn(`AiManager: could not read instructions.txt: ${err.message}`);
      }
    }

    // 4. Built-in default
    logger.info('AiManager: using built-in default instructions');
    return DEFAULT_INSTRUCTIONS;
  }
}

// Export a singleton and the HINT constants so callManager can use them
const instance = new AiManager();
module.exports = instance;
module.exports.HINT = HINT;
module.exports.AiManager = AiManager; // exported for testing with mocked clients
